//-----------------------------------------------------------------------------
//  Holiday.js is part of the BART dashboard widget.  (c) 2005 Bret Victor
//  This software is licensed under the terms of the open source MIT license.
//-----------------------------------------------------------------------------
//
//  Service Levels -- http://www.bart.gov/guide/holidays.aspx
//
//  Automatically generated by make_holiday.pl on Mon Jan 13 19:26:52 2014.
//

function Holiday () {

    servicelevel = {}
    servicelevel['12/25/2013'] = 'sunday'
    servicelevel['01/01/2014'] = 'sunday'
    servicelevel['01/20/2014'] = 'saturday'
    servicelevel['02/17/2014'] = 'saturday'
    servicelevel['05/26/2014'] = 'sunday'
    servicelevel['07/04/2014'] = 'sunday'
    servicelevel['09/01/2014'] = 'saturday'
    servicelevel['11/27/2014'] = 'sunday'
    servicelevel['12/25/2014'] = 'sunday'
    servicelevel['01/01/2015'] = 'sunday'
    
    Holiday.getServiceLevel = function(date) {
        var date_string = date.toMMDDYYYYString()
        var day_of_week = date.getDay()
        
        return servicelevel[date_string] ||
            ( (day_of_week == 0)        ? 'sunday'
            : (day_of_week == 6)        ? 'saturday'
            :                             'weekday')
    }
}

// Open the package.
Holiday();

